---
version: "3"
services:
  watchtower:
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: containrrr/watchtower

  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - DOWNLOAD_DIR=/downloads/MP4
      - AUDIO_DOWNLOAD_DIR=/downloads/MP3
    ports:
      - 8081:8081
    volumes:
      - /mnt/yt:/downloads
      
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - "4533:4533"
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_BASEURL: ""
    volumes:
      - "/mnt/navidrome:/data"
      - "/mnt/music:/music:ro"

  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    volumes:
      - /mnt/docker/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5005:5005
    restart: unless-stopped

  homeassistant:
    image: lscr.io/linuxserver/homeassistant
    container_name: homeassistant
    #network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Chicago/America
    volumes:
      - /mnt/docker/ha/config:/config
    ports:
      - 8123:8123 #optional
    restart: unless-stopped

  linkding:
      image: sissbruecker/linkding:latest
      container_name: linkding
      environment:
          - PUID=1000
          - PGID=1000
          - TZ=Chicago/America
      volumes:
          - /mnt/docker/linkding:/etc/linkding/data
      ports:
          - 9090:9090
      restart: always

  wikijs:
      image:  lscr.io/linuxserver/wikijs
      container_name: wikijs
      environment:
          - PUID=1000
          - PGID=1000
          - TZ=Chicago/America
      volumes:
          - /mnt/docker/wikijs/config:/config
          - /mnt/docker/wikijs/data:/data
      ports:
          - 3000:3000
      restart: unless-stopped
